configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/ronnie-s-test%2Fronnie-beeceptor-api-a579789dc6dd2d067472accb2734e7dc16b94fcfe4453ced2e70c9e0acc95fa5.yml
openapi_spec_hash: 7d5ee1b38fcd18122128ebd8865d384a
config_hash: cef85a1405b4eb7f29908c48f7dbb2eb
